### ISSUE TITLE
!toggle issues

### ISSUE THREAD

**Issue by buzztiaan** [folkertvanheusden/GHBot#3]
> 21:43:08 <@buZz> oja, en een ander issue, !toggle werkt nogal anders :P
> 21:43:10 <@buZz> !toggle arcade
> 21:43:11 <@ghbot> Exception during "toggle": name 'find_devices' is not defined, line number: 336
> 21:43:14 <@buZz> !toggle-list arcade
> 21:43:14 <@ghbot> 4: Arcade
> 21:43:21 <@buZz> het is 1 optie, waarom dan moeite? :P
> 21:43:25 <@buZz> !toggle Arcade
> 21:43:25 <@ghbot> Exception during "toggle": name 'find_devices' is not defined, line number: 336
> 21:44:00 <@flok> buZz: graag in de github of de nurdspace-wiki-pagina want ikg a 't niet onthouden allemaal
> 21:44:06 <@buZz> ohja ok
> 21:44:23 <@flok> dank

**Comment by folkertvanheusden** [comment]
Should be fixed in the latest hass-plugin release.

**Comment by buzztiaan** [comment]
oh woot, update next saturday while at space? :P
